"""add tracks table

Revision ID: 43aa2e7ecfe9
Revises:
Create Date: 2026-02-14 20:37:34.647521
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43aa2e7ecfe9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("artist", sa.String(length=500), nullable=True),
        sa.Column("album", sa.String(length=500), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("file_hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("chromaprint_fingerprint", sa.Text(), nullable=True),
        sa.Column("chromaprint_duration", sa.Float(), nullable=True),
        sa.Column("olaf_indexed", sa.Boolean(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_hash_sha256"),
    )
    op.create_index("ix_tracks_artist_title", "tracks", ["artist", "title"], unique=False)
    op.create_index("ix_tracks_file_hash", "tracks", ["file_hash_sha256"], unique=True)
    op.create_index("ix_tracks_ingested_at", "tracks", ["ingested_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tracks_ingested_at", table_name="tracks")
    op.drop_index("ix_tracks_file_hash", table_name="tracks")
    op.drop_index("ix_tracks_artist_title", table_name="tracks")
    op.drop_table("tracks")
    # ### end Alembic commands ###
