/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Audio
         * @description Search for audio matches using fingerprint (exact) and/or
         *     embedding (vibe) similarity.
         *
         *     Accepts multipart/form-data with:
         *     - ``audio``: The audio file to search for
         *     - ``mode``: Search mode (``"exact"``, ``"vibe"``, or ``"both"``)
         *     - ``max_results``: Max results per lane (1-50, default 10)
         */
        post: operations["search_audio_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tracks
         * @description Return a paginated list of tracks, optionally filtered by title/artist search.
         */
        get: operations["list_tracks_api_v1_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Track
         * @description Return full detail for a single track by UUID.
         */
        get: operations["get_track_api_v1_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_search_audio_api_v1_search_post */
        Body_search_audio_api_v1_search_post: {
            /**
             * Audio
             * Format: binary
             * @description Audio file (WebM/Opus, MP3, MP4/AAC, WAV). Max 10 MB.
             */
            audio: string;
            /** @default both */
            mode: components["schemas"]["SearchMode"];
            /**
             * Max Results
             * @default 10
             */
            max_results: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ExactMatch
         * @description Result from the fingerprint (exact identification) lane.
         */
        ExactMatch: {
            track: components["schemas"]["TrackInfo"];
            /** Confidence */
            confidence: number;
            /** Offset Seconds */
            offset_seconds?: number | null;
            /** Aligned Hashes */
            aligned_hashes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** PaginatedResponse[TrackInfo] */
        PaginatedResponse_TrackInfo_: {
            /** Data */
            data: components["schemas"]["TrackInfo"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalitems */
            totalItems: number;
            /** Totalpages */
            totalPages: number;
        };
        /**
         * SearchMode
         * @enum {string}
         */
        SearchMode: "exact" | "vibe" | "both";
        /**
         * SearchResponse
         * @description Combined response from both search lanes.
         */
        SearchResponse: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Query Duration Ms */
            query_duration_ms: number;
            /** Exact Matches */
            exact_matches?: components["schemas"]["ExactMatch"][];
            /** Vibe Matches */
            vibe_matches?: components["schemas"]["VibeMatch"][];
            mode_used: components["schemas"]["SearchMode"];
        };
        /**
         * TrackDetail
         * @description Full track detail including audio properties and indexing status.
         */
        TrackDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist?: string | null;
            /** Album */
            album?: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Channels */
            channels?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Format */
            format?: string | null;
            /** File Hash Sha256 */
            file_hash_sha256: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Olaf Indexed */
            olaf_indexed: boolean;
            /** Embedding Model */
            embedding_model?: string | null;
            /** Embedding Dim */
            embedding_dim?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TrackInfo
         * @description Minimal track metadata returned in search results.
         */
        TrackInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist?: string | null;
            /** Album */
            album?: string | null;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Git Sha */
            git_sha: string;
            /** Build Time */
            build_time: string;
        };
        /**
         * VibeMatch
         * @description Result from the embedding (vibe/similarity) lane.
         */
        VibeMatch: {
            track: components["schemas"]["TrackInfo"];
            /** Similarity */
            similarity: number;
            /** Embedding Model */
            embedding_model: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    search_audio_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_search_audio_api_v1_search_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error (format, size, duration) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Search service unavailable (both lanes failed) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Search timed out (both lanes timed out) */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tracks_api_v1_tracks_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_TrackInfo_"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_track_api_v1_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetail"];
                };
            };
            /** @description Track not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
